linters:
- import:
    packages: ['chemtools']
    filefilter: ['- scripts/*.py']
- namespace:
    filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '- tools/*', '- examples/*/*.py', '- scripts/*.py',
                 '+ *.py', '+ */*.py', '*.conf']
- pylint:
    config: .pylintrc
- pycodestyle:
    config: .pycodestylerc
- pydocstyle:
    config: .pydocstylerc
- whitespace:
    filefilter: ['- data/test/*']
