linters:
- import:
    packages: ['chemtools']
    filefilter: ['- scripts/*.py']
- pylint:
    config: .pylintrc
- pycodestyle:
    config: .pycodestylerc
- pydocstyle:
    config: .pydocstylerc
- whitespace:
    filefilter: ['- data/test/*']
