linters:
- import:
    packages: ['chemtools']
- namespace:
    filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '- tools/*', '- examples/*/*.py',
                 '+ *.py', '+ */*.py']
- pylint:
    config: .pylintrc
- pycodestyle:
    config: .pycodestylerc
- pydocstyle:
    config: .pydocstylerc
- whitespace:
